//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaystationApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlaystationApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me:.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string AboutMeCategory {
            get {
                return ResourceManager.GetString("AboutMeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add As Friend.
        /// </summary>
        public static string AddAsFriend {
            get {
                return ResourceManager.GetString("AddAsFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Friend Request.
        /// </summary>
        public static string CancelFriendRequest {
            get {
                return ResourceManager.GetString("CancelFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Name Request.
        /// </summary>
        public static string CancelNameRequest {
            get {
                return ResourceManager.GetString("CancelNameRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cancel the name request..
        /// </summary>
        public static string CancelNameRequestError {
            get {
                return ResourceManager.GetString("CancelNameRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Friend Request.
        /// </summary>
        public static string DeleteFriendRequest {
            get {
                return ResourceManager.GetString("DeleteFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Name Request.
        /// </summary>
        public static string DeleteNameRequest {
            get {
                return ResourceManager.GetString("DeleteNameRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dislike.
        /// </summary>
        public static string DislikeButton {
            get {
                return ResourceManager.GetString("DislikeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Friend Request.
        /// </summary>
        public static string FriendRequest {
            get {
                return ResourceManager.GetString("FriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add this player as a Friend?.
        /// </summary>
        public static string FriendRequestAlert {
            get {
                return ResourceManager.GetString("FriendRequestAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Friend request will be sent to this player..
        /// </summary>
        public static string FriendRequestConfirm {
            get {
                return ResourceManager.GetString("FriendRequestConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Requests (Received).
        /// </summary>
        public static string FriendRequestReceived {
            get {
                return ResourceManager.GetString("FriendRequestReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Requests (Sent).
        /// </summary>
        public static string FriendRequestSent {
            get {
                return ResourceManager.GetString("FriendRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send the Friend Request..
        /// </summary>
        public static string FriendSendError {
            get {
                return ResourceManager.GetString("FriendSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string FriendsFilterAll {
            get {
                return ResourceManager.GetString("FriendsFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Players.
        /// </summary>
        public static string FriendsFilterBlockedPlayer {
            get {
                return ResourceManager.GetString("FriendsFilterBlockedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Requests (Received).
        /// </summary>
        public static string FriendsFilterNameRequestReceived {
            get {
                return ResourceManager.GetString("FriendsFilterNameRequestReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Requests (Sent).
        /// </summary>
        public static string FriendsFilterNameRequestSent {
            get {
                return ResourceManager.GetString("FriendsFilterNameRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string FriendsFilterOnline {
            get {
                return ResourceManager.GetString("FriendsFilterOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players Met.
        /// </summary>
        public static string FriendsFilterPlayersMet {
            get {
                return ResourceManager.GetString("FriendsFilterPlayersMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Requests (Received).
        /// </summary>
        public static string FriendsFilterRequestReceived {
            get {
                return ResourceManager.GetString("FriendsFilterRequestReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Requests (Sent).
        /// </summary>
        public static string FriendsFilterRequestSent {
            get {
                return ResourceManager.GetString("FriendsFilterRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string FriendsPivot {
            get {
                return ResourceManager.GetString("FriendsPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Friends.
        /// </summary>
        public static string FriendTotal {
            get {
                return ResourceManager.GetString("FriendTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (o_0)An Error Has Occured(O_o).
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Trophy.
        /// </summary>
        public static string HiddenTrophy {
            get {
                return ResourceManager.GetString("HiddenTrophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Simplified).
        /// </summary>
        public static string LangChineseSimplified {
            get {
                return ResourceManager.GetString("LangChineseSimplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Traditional).
        /// </summary>
        public static string LangChineseTraditional {
            get {
                return ResourceManager.GetString("LangChineseTraditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string LangDanish {
            get {
                return ResourceManager.GetString("LangDanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string LangDutch {
            get {
                return ResourceManager.GetString("LangDutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (United Kingdom).
        /// </summary>
        public static string LangEnglishUK {
            get {
                return ResourceManager.GetString("LangEnglishUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (United States).
        /// </summary>
        public static string LangEnglishUS {
            get {
                return ResourceManager.GetString("LangEnglishUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        public static string LangFinnish {
            get {
                return ResourceManager.GetString("LangFinnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string LangFrench {
            get {
                return ResourceManager.GetString("LangFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string LangGerman {
            get {
                return ResourceManager.GetString("LangGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string LangItalian {
            get {
                return ResourceManager.GetString("LangItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string LangJapanese {
            get {
                return ResourceManager.GetString("LangJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string LangKorean {
            get {
                return ResourceManager.GetString("LangKorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        public static string LangNorwegian {
            get {
                return ResourceManager.GetString("LangNorwegian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string LangPolish {
            get {
                return ResourceManager.GetString("LangPolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Brazil).
        /// </summary>
        public static string LangPortugueseBrazil {
            get {
                return ResourceManager.GetString("LangPortugueseBrazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Portugal).
        /// </summary>
        public static string LangPortuguesePortugal {
            get {
                return ResourceManager.GetString("LangPortuguesePortugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string LangRussian {
            get {
                return ResourceManager.GetString("LangRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (Latin America).
        /// </summary>
        public static string LangSpanishLA {
            get {
                return ResourceManager.GetString("LangSpanishLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (Spain).
        /// </summary>
        public static string LangSpanishSpain {
            get {
                return ResourceManager.GetString("LangSpanishSpain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string LangSwedish {
            get {
                return ResourceManager.GetString("LangSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string LangTurkish {
            get {
                return ResourceManager.GetString("LangTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string LikeButton {
            get {
                return ResourceManager.GetString("LikeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MessagesPivot {
            get {
                return ResourceManager.GetString("MessagesPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Languages:.
        /// </summary>
        public static string MyLanguages {
            get {
                return ResourceManager.GetString("MyLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reveal your name to this Friend?.
        /// </summary>
        public static string NameRequestAlert {
            get {
                return ResourceManager.GetString("NameRequestAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Request (Received).
        /// </summary>
        public static string NameRequestReceived {
            get {
                return ResourceManager.GetString("NameRequestReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send the name request..
        /// </summary>
        public static string NameRequestSendError {
            get {
                return ResourceManager.GetString("NameRequestSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Request (Sent).
        /// </summary>
        public static string NameRequestSent {
            get {
                return ResourceManager.GetString("NameRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no activities..
        /// </summary>
        public static string NoActivities {
            get {
                return ResourceManager.GetString("NoActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Friends Found..
        /// </summary>
        public static string NoFriends {
            get {
                return ResourceManager.GetString("NoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no new game alerts..
        /// </summary>
        public static string NoGameAlert {
            get {
                return ResourceManager.GetString("NoGameAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no new messages..
        /// </summary>
        public static string NoMessages {
            get {
                return ResourceManager.GetString("NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no new notifications..
        /// </summary>
        public static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No players found..
        /// </summary>
        public static string NoPlayers {
            get {
                return ResourceManager.GetString("NoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NotificationsHeader {
            get {
                return ResourceManager.GetString("NotificationsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no trophies.
        ///You can earn trophies by playing games that support them..
        /// </summary>
        public static string NoTrophyInfo {
            get {
                return ResourceManager.GetString("NoTrophyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Playing.
        /// </summary>
        public static string NowPlaying {
            get {
                return ResourceManager.GetString("NowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileHeader {
            get {
                return ResourceManager.GetString("ProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Name Request.
        /// </summary>
        public static string RealNameRequest {
            get {
                return ResourceManager.GetString("RealNameRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activity.
        /// </summary>
        public static string RecentActivity {
            get {
                return ResourceManager.GetString("RecentActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Friends.
        /// </summary>
        public static string RemoveFromFriends {
            get {
                return ResourceManager.GetString("RemoveFromFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reveal Name.
        /// </summary>
        public static string RevealName {
            get {
                return ResourceManager.GetString("RevealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To {0}.
        /// </summary>
        public static string ToMessageHeader {
            get {
                return ResourceManager.GetString("ToMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Friends.
        /// </summary>
        public static string TotalFriends {
            get {
                return ResourceManager.GetString("TotalFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze.
        /// </summary>
        public static string TrophyBronze {
            get {
                return ResourceManager.GetString("TrophyBronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string TrophyCommon {
            get {
                return ResourceManager.GetString("TrophyCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string TrophyDetail {
            get {
                return ResourceManager.GetString("TrophyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned.
        /// </summary>
        public static string TrophyEarned {
            get {
                return ResourceManager.GetString("TrophyEarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned Date.
        /// </summary>
        public static string TrophyEarnedDate {
            get {
                return ResourceManager.GetString("TrophyEarnedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string TrophyGold {
            get {
                return ResourceManager.GetString("TrophyGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string TrophyGrade {
            get {
                return ResourceManager.GetString("TrophyGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trophies.
        /// </summary>
        public static string TrophyHeader {
            get {
                return ResourceManager.GetString("TrophyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string TrophyHidden {
            get {
                return ResourceManager.GetString("TrophyHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Earned.
        /// </summary>
        public static string TrophyNotEarned {
            get {
                return ResourceManager.GetString("TrophyNotEarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum.
        /// </summary>
        public static string TrophyPlatinum {
            get {
                return ResourceManager.GetString("TrophyPlatinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        public static string TrophyRare {
            get {
                return ResourceManager.GetString("TrophyRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity.
        /// </summary>
        public static string TrophyRarity {
            get {
                return ResourceManager.GetString("TrophyRarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string TrophySilver {
            get {
                return ResourceManager.GetString("TrophySilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TrophyStatus {
            get {
                return ResourceManager.GetString("TrophyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string TrophyTotal {
            get {
                return ResourceManager.GetString("TrophyTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra Rare.
        /// </summary>
        public static string TrophyUltraRare {
            get {
                return ResourceManager.GetString("TrophyUltraRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Rare.
        /// </summary>
        public static string TrophyVeryRare {
            get {
                return ResourceManager.GetString("TrophyVeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Search.
        /// </summary>
        public static string UserSearch {
            get {
                return ResourceManager.GetString("UserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Friend Request.
        /// </summary>
        public static string ViewFriendRequest {
            get {
                return ResourceManager.GetString("ViewFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Information.
        /// </summary>
        public static string ViewInformation {
            get {
                return ResourceManager.GetString("ViewInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Name Request.
        /// </summary>
        public static string ViewNameRequest {
            get {
                return ResourceManager.GetString("ViewNameRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Message.
        /// </summary>
        public static string VoiceMessage {
            get {
                return ResourceManager.GetString("VoiceMessage", resourceCulture);
            }
        }
    }
}
